<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Addresses.aspx.cs" MasterPageFile="~/Site.Master" Inherits="CW.Addresses" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>Addresses</h1>
        <div class="form-horizontal">
          <div class="form-group p-3">
            <label for="area" class="col-sm-2 control-label">Area</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtArea" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorArea" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtArea" ForeColor="Red"></asp:RequiredFieldValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="longitude" class="col-sm-2 control-label">Longitude</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtLongitude" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLongitude" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtLongitude" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:RegularExpressionValidator Display="Dynamic" ID="RegularExpressionValidatorLongitude" runat="server" ControlToValidate="txtLongitude" ForeColor="Red" ErrorMessage="*Invalid Longitude Value" ValidationExpression="^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$"></asp:RegularExpressionValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="latitude" class="col-sm-2 control-label">Latitude</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtLatitude" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLatitude" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtLatitude" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:RegularExpressionValidator Display="Dynamic" ID="RegularExpressionValidatorLatitude" runat="server" ControlToValidate="txtLatitude" ForeColor="Red" ErrorMessage="*Invalid Latitude Value" ValidationExpression="^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$"></asp:RegularExpressionValidator>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Button ID="Button1" class="btn btn-default" runat="server" ValidationGroup="insert" Text="Submit" OnClick="Button1_Click" />
              <asp:Button ID="Button2" class="btn btn-default" runat="server" Text="Reset" CausesValidation="false" OnClick="Button2_Click" />
            </div>
          </div>
          <asp:CustomValidator Display="Dynamic" ID="CustomValidatorGrid" runat="server" ForeColor="Red" ErrorMessage="* Update failed due to invalid data. Please try again."></asp:CustomValidator>
          <asp:GridView ID="GridView1" class="table table-hover table-bordered" runat="server" DataKeyNames="ADDRESS_ID" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowDataBound="GridView1_RowDataBound" OnRowEditing="GridView1_RowEditing" EmptyDataText="No records have been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
          </asp:GridView>
        </div>
    </div>
</asp:Content>
