<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Customers.aspx.cs" MasterPageFile="~/Site.Master" Inherits="CW.Customers" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>Customers</h1>
        <div class="form-horizontal">
          <div class="form-group p-3">
            <label for="customerName" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtCustomerName" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorName" runat="server" ErrorMessage="*Required" ControlToValidate="txtCustomerName" ForeColor="Red"></asp:RequiredFieldValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="customerEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtCustomerEmail" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorEmail" runat="server" ErrorMessage="*Required" ControlToValidate="txtCustomerEmail" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:RegularExpressionValidator Display="Dynamic" ID="RegularExpressionValidatorEmail" runat="server" ControlToValidate="txtCustomerEmail" ErrorMessage="*Please Enter Valid Email" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="customerPhone" class="col-sm-2 control-label">Phone No.</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtCustomerPhone" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorPhone" runat="server" ErrorMessage="*Required" ControlToValidate="txtCustomerPhone" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:RegularExpressionValidator Display="Dynamic" ID="RegularExpressionValidatorPhone" ControlToValidate="txtCustomerPhone" runat="server" ErrorMessage="*Please Enter a Valid Phone" ValidationExpression="\d{10}" ForeColor="Red"></asp:RegularExpressionValidator></div>
          </div>
          <div class="form-group">
            <label for="customerLPoints" class="col-sm-2 control-label">Total Loyalty Points</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtCustomerLP" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLP" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtCustomerLP" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:CompareValidator Display="Dynamic" ID="CompareValidatorLP" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="txtCustomerLP" ErrorMessage="*Value must be a whole number" ForeColor="Red" />
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Button ID="Button1" class="btn btn-default" ValidationGroup="insert" runat="server" Text="Submit" OnClick="Button1_Click"/>
              <asp:Button ID="Button2" class="btn btn-default" runat="server" Text="Reset" CausesValidation="false" OnClick="Button2_Click"/>
            </div>
          </div>
          <asp:CustomValidator Display="Dynamic" ID="CustomValidatorGrid" runat="server" ForeColor="Red" ErrorMessage="* Update failed due to invalid data. Please try again."></asp:CustomValidator>
          <asp:GridView ID="GridView1" style="overflow-x:scroll;" class="table table-hover table-bordered" runat="server" DataKeyNames="CUSTOMER_ID" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowDataBound="GridView1_RowDataBound" OnRowEditing="GridView1_RowEditing" EmptyDataText="No records have been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
          </asp:GridView>
        </div>
    </div>
</asp:Content>
