<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dishes.aspx.cs" MasterPageFile="~/Site.Master" Inherits="CW.Dishes" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>Dishes</h1>
        <div class="form-horizontal">
          <div class="form-group">
            <label for="dishName" class="col-sm-2 control-label">Dish Name</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtDishName" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorDishName" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtDishName" ForeColor="Red"></asp:RequiredFieldValidator>
            </div>
          </div>
            <div class="form-group">
            <label for="localName" class="col-sm-2 control-label">Local Name</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtLocalName" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLocalName" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtLocalName" ForeColor="Red"></asp:RequiredFieldValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="dishLP" class="col-sm-2 control-label">Loyalty Points</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtLP" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLP" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtLP" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:CompareValidator Display="Dynamic" ID="CompareValidatorLP" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="txtLP" ErrorMessage="*Value must be a whole number" ForeColor="Red" />
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Button ID="Button1" class="btn btn-default" ValidationGroup="insert" runat="server" Text="Submit" OnClick="Button1_Click"/>
              <asp:Button ID="Button2" class="btn btn-default" runat="server" Text="Reset" CausesValidation="false" OnClick="Button2_Click"/>
            </div>
          </div>
          <asp:CustomValidator Display="Dynamic" ID="CustomValidatorGrid" runat="server" ForeColor="Red" ErrorMessage="* Update failed due to invalid data. Please try again."></asp:CustomValidator>
          <asp:GridView ID="GridView1" class="table table-hover table-bordered" runat="server" DataKeyNames="DISH_CODE" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowDataBound="GridView1_RowDataBound" OnRowEditing="GridView1_RowEditing" EmptyDataText="No records have been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
          </asp:GridView>
        </div>
    </div>
</asp:Content>
