<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="LPoints.aspx.cs" MasterPageFile="~/Site.Master" Inherits="CW.LPoints" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>Loylaty Points Dates</h1>
        <div class="form-horizontal">
          <div class="form-group p-3">
            <label for="dishCodeLP" class="col-sm-2 control-label">Dish Code</label>
            <div class="col-sm-10">
              <asp:DropDownList ID="ddlDishes" class="form-control" OnDataBound="ddlDishes_DataBound" runat="server" DataSourceID="SqlDataSource1" DataTextField="DISH_NAME" DataValueField="DISH_CODE"></asp:DropDownList>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorDish" runat="server" ControlToValidate="ddlDishes" ErrorMessage="*Required" ForeColor="Red" InitialValue="Select Dish"></asp:RequiredFieldValidator>
              <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT &quot;DISH_NAME&quot;, &quot;DISH_CODE&quot; FROM &quot;DISHES&quot;"></asp:SqlDataSource>
            </div>
          </div>
          <div class="form-group">
            <label for="lpdate" class="col-sm-2 control-label">Applicable Date</label>
            <div class="col-sm-10">
               <asp:TextBox ID="txtLPDate" class="form-control" placeholder="dd-mmm-yy" ReadOnly="true" runat="server"></asp:TextBox>
               <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorLPDate" runat="server" ControlToValidate="txtLPDate" ForeColor="Red" ErrorMessage="*Required"></asp:RequiredFieldValidator>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Button ID="Button3" class="btn btn-default btn-sm" OnClick="Button3_Click" CausesValidation="false" runat="server" Text="Pick Date"/>
              <span class="glyphicon glyphicon-calendar"></span>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Calendar ID="lpDate" OnSelectionChanged="lpDate_SelectionChanged" runat="server"></asp:Calendar>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <asp:Button ID="Button1" class="btn btn-default" ValidationGroup="insert" runat="server" Text="Submit" OnClick="Button1_Click" />
              <asp:Button ID="Button2" class="btn btn-default" runat="server" Text="Reset" CausesValidation="false" OnClick="Button2_Click" />
            </div>
          </div>
          <asp:CustomValidator Display="Dynamic" ID="CustomValidatorGrid" runat="server" ForeColor="Red" ErrorMessage="* Update failed due to invalid data. Please try again."></asp:CustomValidator>
          <asp:GridView ID="GridView1" class="table table-hover table-bordered" runat="server" DataKeyNames="DISH_DATE_ID" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowDataBound="GridView1_RowDataBound" OnRowEditing="GridView1_RowEditing" EmptyDataText="No records have been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
          </asp:GridView>
        </div>
    </div>
</asp:Content>
