<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Restaurants.aspx.cs" MasterPageFile="~/Site.Master" Inherits="CW.Restaurants" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <h1>Restaurants</h1>
        <div class="form-horizontal">
          <div class="form-group p-3">
            <label for="restaurantName" class="col-sm-2 control-label">Restaurant's Name</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtRestaurantName" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorRName" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtRestaurantName" ForeColor="Red"></asp:RequiredFieldValidator>
            </div>
          </div>
          <div class="form-group">
            <label for="restaurantEmail" class="col-sm-2 control-label">Restaurant's Address</label>
            <div class="col-sm-10">
                <asp:DropDownList ID="ddlAddresses" OnDataBound="ddlAddresses_DataBound" class="form-control" runat="server" DataSourceID="SqlDataSource1" DataTextField="AREA" DataValueField="ADDRESS_ID"></asp:DropDownList>
                <asp:RequiredFieldValidator ValidationGroup="insert" ID="RequiredFieldValidatorAddress" ControlToValidate="ddlAddresses" Display="Dynamic" runat="server" ErrorMessage="*Required" ForeColor="Red" InitialValue="Select Address"></asp:RequiredFieldValidator>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT &quot;ADDRESS_ID&quot;, &quot;AREA&quot; FROM &quot;ADDRESSES&quot;"></asp:SqlDataSource>
            </div>
          </div>
          <div class="form-group">
            <label for="restaurantContact" class="col-sm-2 control-label">Contact No.</label>
            <div class="col-sm-10">
              <asp:TextBox ID="txtRestaurantContact" class="form-control" runat="server"></asp:TextBox>
              <asp:RequiredFieldValidator ValidationGroup="insert" Display="Dynamic" ID="RequiredFieldValidatorRContact" runat="server" ErrorMessage="*Required Field" ControlToValidate="txtRestaurantContact" ForeColor="Red"></asp:RequiredFieldValidator>
              <asp:RegularExpressionValidator Display="Dynamic" ID="RegularExpressionValidatorRContact" ControlToValidate="txtRestaurantContact" runat="server" ErrorMessage="*Invalid Phone No." ValidationExpression="\d{10}" ForeColor="Red"></asp:RegularExpressionValidator>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <asp:Button ID="Button1" class="btn btn-default" ValidationGroup="insert" runat="server" Text="Submit" OnClick="Button1_Click" />
                <asp:Button ID="Button2" class="btn btn-default" runat="server" Text="Reset" CausesValidation="false" OnClick="Button2_Click" />
            </div>
          </div>
          <asp:CustomValidator Display="Dynamic" ID="CustomValidatorGrid" runat="server" ForeColor="Red" ErrorMessage="* Update failed due to invalid data. Please try again."></asp:CustomValidator>
          <asp:GridView ID="GridView1" class="table table-hover table-bordered" runat="server" DataKeyNames="RESTAURANT_ID" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowDataBound="GridView1_RowDataBound" OnRowEditing="GridView1_RowEditing" EmptyDataText="No records have been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
          </asp:GridView>
        </div>
    </div>
</asp:Content>
